# Generated by Django 6.0.8 on 2026-09-07 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_businessrule_card_category_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-occurred_at', '-id'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='effective_at',
            field=models.DateField(default=datetime.date(1970, 1, 1), editable=False, verbose_name='Data Efetiva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='occurred_at',
            field=models.DateField(verbose_name='Data da Transação'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('card__isnull', False), ('method', 'CREDIT')), models.Q(models.Q(('method', 'CREDIT'), _negated=True), ('card__isnull', True)), _connector='OR'), name='transaction_card_only_on_credit', violation_error_message='Transações em Crédito exigem um cartão, e o cartão só se aplica a esse método.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('nature', 'REGULAR'), ('category__isnull', True), _connector='OR'), name='transaction_category_only_when_regular', violation_error_message='Apenas transações com natureza Normal recebem categoria.'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-effective_at'], name='transaction_effective_at_idx'),
        ),
    ]
