# Generated by Django 6.0.7 on 2026-08-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_transaction_unique_transaction_external_id_per_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Data e Hora')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Rendido')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='app.investment', verbose_name='Investimento')),
            ],
            options={
                'verbose_name': 'Rendimento',
                'verbose_name_plural': 'Rendimentos',
                'ordering': ['-datetime'],
                'abstract': False,
            },
        ),
    ]
