# Generated by Django 6.0.8 on 2026-09-08 01:33

import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transaction_options_transaction_effective_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('description'), name='account_unique_description', violation_error_message='Já existe uma conta com essa descrição.'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('closing_day__range', (1, 31)), ('due_day__range', (1, 31))), name='card_days_within_month', violation_error_message='Os dias de fechamento e vencimento devem estar entre 1 e 31.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('description'), name='category_unique_description', violation_error_message='Já existe uma categoria com essa descrição.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.01'))), name='transaction_value_positive', violation_error_message='O valor deve ser maior que zero.'),
        ),
    ]
