# Generated by Django 6.0.7 on 2026-08-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_yield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='type',
        ),
    ]
