# Generated by Django 6.0.8 on 2026-09-08 21:52

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_transaction_transaction_user_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parcel',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Parcela'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('installments', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(360)], verbose_name='Número de Parcelas')),
                ('occurred_at', models.DateField(verbose_name='Data da Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='app.account', verbose_name='Conta')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='app.card', verbose_name='Cartão')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='app.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.installment', verbose_name='Parcelamento'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('installment__isnull', False), ('parcel__isnull', False)), models.Q(('installment__isnull', True), ('parcel__isnull', True)), _connector='OR'), name='transaction_parcel_only_within_installment', violation_error_message='O número da parcela só existe em transações de um parcelamento.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('installment', 'parcel'), name='transaction_unique_installment_parcel', violation_error_message='O parcelamento já tem uma transação com esse número de parcela.'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.01'))), name='installment_value_positive', violation_error_message='O valor deve ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('installments__range', (2, 360))), name='installment_parcels_within_range', violation_error_message='Um parcelamento deve ter de 2 a 360 parcelas.'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', django.db.models.expressions.CombinedExpression(models.F('installments'), '*', models.Value(Decimal('0.01'))))), name='installment_value_covers_parcels', violation_error_message='O valor deve dar ao menos um centavo para cada parcela.'),
        ),
    ]
