# Generated by Django 6.0.7 on 2026-08-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transaction_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('REGULAR', 'Normal'), ('INTERNAL', 'Movimentação Interna'), ('ADJUSTMENT', 'Ajuste de Saldo')], default='REGULAR', help_text='Movimentação interna e ajuste contam no saldo, mas ficam fora dos gráficos.', max_length=20, verbose_name='Natureza'),
        ),
    ]
