# Generated by Django 6.0.8 on 2026-09-08 22:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_parcel_installment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('occurred_at', models.DateField(verbose_name='Data da Transferência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='app.account', verbose_name='Conta de Destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='app.account', verbose_name='Conta de Origem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.transfer', verbose_name='Transferência'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('transfer', 'type'), name='transaction_unique_transfer_leg', violation_error_message='A transferência já tem uma transação desse tipo.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment__isnull', False), ('transfer__isnull', False), _negated=True), name='transaction_single_origin', violation_error_message='Uma transação vem de um parcelamento ou de uma transferência, nunca dos dois.'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.01'))), name='transfer_value_positive', violation_error_message='O valor deve ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='transfer_accounts_differ', violation_error_message='A conta de destino deve ser diferente da conta de origem.'),
        ),
    ]
