# Generated by Django 6.0.8 on 2026-09-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transfer_transaction_transfer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment__isnull', True), ('nature', 'REGULAR'), _connector='OR'), name='transaction_parcel_is_regular', violation_error_message='A parcela de um parcelamento é sempre de natureza Normal.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer__isnull', True), ('nature', 'INTERNAL'), _connector='OR'), name='transaction_transfer_leg_is_internal', violation_error_message='A perna de uma transferência é sempre de natureza Movimentação Interna.'),
        ),
    ]
