# Generated by Django 6.0.8 on 2026-09-09 21:33

import app.models.subscription_period
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_transaction_parcel_is_regular_and_more'),
    ]

    operations = [
        # O GiST só compara subscription_id com = depois desta extensão.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='O nome do serviço. Ex.: Spotify, Netflix, Claude.', max_length=200, verbose_name='Assinatura')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Cobrança')),
                ('recurrence', models.PositiveSmallIntegerField(choices=[(1, 'Mensal'), (2, 'Bimestral'), (3, 'Trimestral'), (6, 'Semestral'), (12, 'Anual')], default=1, verbose_name='Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(help_text='A data da primeira cobrança deste período. O dia dela é o dia usado nas cobranças seguintes.', verbose_name='Data da Primeira Cobrança')),
                ('cancelled_at', models.DateField(blank=True, help_text='Deixe em branco enquanto o período estiver ativo. A cobrança que cai até esta data ainda é gerada.', null=True, verbose_name='Data do Encerramento')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['subscription__description', 'started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_single_origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='app.card', verbose_name='Cartão'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='app.subscription', verbose_name='Assinatura'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('installment__isnull', False), ('transfer__isnull', False), _negated=True), models.Q(('installment__isnull', False), ('subscription__isnull', False), _negated=True), models.Q(('subscription__isnull', False), ('transfer__isnull', False), _negated=True)), name='transaction_single_origin', violation_error_message='Uma transação vem de um parcelamento, de uma transferência ou de uma assinatura, nunca de mais de um.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference__isnull', False), ('subscription__isnull', False)), models.Q(('reference__isnull', True), ('subscription__isnull', True)), _connector='OR'), name='transaction_reference_only_within_subscription', violation_error_message='A competência só existe em transações de uma assinatura.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('subscription', 'reference'), name='transaction_unique_subscription_reference', violation_error_message='A assinatura já tem uma cobrança nessa competência.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('subscription__isnull', True), ('nature', 'REGULAR'), _connector='OR'), name='transaction_subscription_charge_is_regular', violation_error_message='A cobrança de uma assinatura é sempre de natureza Normal.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('subscription__isnull', True), ('reference', django.db.models.functions.datetime.TruncMonth('occurred_at')), _connector='OR'), name='transaction_charge_within_reference', violation_error_message='A data da cobrança precisa cair dentro da competência.'),
        ),
        migrations.AddField(
            model_name='subscriptionperiod',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.subscription', verbose_name='Assinatura'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.01'))), name='subscription_value_positive', violation_error_message='O valor deve ser maior que zero.'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence__in', [1, 2, 3, 6, 12])), name='subscription_recurrence_within_choices', violation_error_message='A recorrência precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), ('cancelled_at__gte', models.F('started_at')), _connector='OR'), name='subscription_period_cancelled_after_start', violation_error_message='O encerramento não pode ser anterior à primeira cobrança do período.'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('subscription',), name='subscription_period_single_open', violation_error_message='A assinatura já tem um período em aberto.'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=models.UniqueConstraint(fields=('subscription', 'started_at'), name='subscription_period_unique_start', violation_error_message='A assinatura já tem um período que começa nessa data.'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(app.models.subscription_period.DateRange('started_at', 'cancelled_at', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_upper=True)), '&&'), ('subscription', '=')], name='subscription_period_no_overlap', violation_error_message='Este período se sobrepõe a outro da mesma assinatura.'),
        ),
    ]
