# Generated by Django 6.0.8 on 2026-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscription_subscriptionperiod_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessrule',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['IN', 'OUT'])), name='business_rule_type_within_choices', violation_error_message='O tipo precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='businessrule',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['CREDIT', 'DEBIT', 'NOT_APPLICABLE'])), name='business_rule_method_within_choices', violation_error_message='O método precisa ser uma das opções previstas.'),
        ),
        migrations.AlterConstraint(
            model_name='businessrule',
            name='business_rule_unique_combination',
            constraint=models.UniqueConstraint(fields=('account', 'type', 'method'), name='business_rule_unique_combination', violation_error_message='Essa conta já tem uma regra com esse tipo e método.'),
        ),
    ]
