# Generated by Django 6.0.8 on 2026-08-31 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_card_user_alter_card_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Onde esta credencial é usada. Ex.: Agente n8n.', max_length=100, verbose_name='Descrição')),
                ('digest', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Resumo do Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('last_used', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último Uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Credencial de API',
                'verbose_name_plural': 'Credenciais de API',
                'ordering': ['user__username', 'description'],
                'unique_together': {('user', 'description')},
            },
        ),
    ]
