# Generated by Django 6.0.8 on 2026-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_businessrule_business_rule_type_within_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='closing_day',
            field=models.PositiveSmallIntegerField(verbose_name='Dia de Fechamento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_day',
            field=models.PositiveSmallIntegerField(verbose_name='Dia de Vencimento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_digits',
            field=models.CharField(max_length=4, verbose_name='Últimos Quatro Dígitos'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('last_digits__regex', '^\\d{4}$')), name='card_last_digits_four_numbers', violation_error_message='Informe exatamente os últimos quatro dígitos do cartão.'),
        ),
        migrations.AlterConstraint(
            model_name='card',
            name='card_unique_user_account_digits',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'last_digits'), name='card_unique_user_account_digits', violation_error_message='Esse cartão já foi cadastrado.'),
        ),
    ]
