# Generated by Django 6.0.8 on 2026-09-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_card_closing_day_alter_card_due_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='installments',
            field=models.PositiveSmallIntegerField(verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
