# Generated by Django 6.0.8 on 2026-09-01 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_transaction_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='api_token',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-updated'],
                'permissions': [('use_assistant', 'Pode usar o assistente')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('tool', 'Ferramenta')], max_length=20, verbose_name='Papel')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('tool_calls', models.JSONField(blank=True, null=True, verbose_name='Chamadas de Ferramenta')),
                ('tool_call_id', models.CharField(blank=True, max_length=100, verbose_name='Id da Chamada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PendingWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='Tipo de Lançamento')),
                ('payload', models.JSONField(verbose_name='Dados do Lançamento')),
                ('summary', models.JSONField(verbose_name='Resumo Exibido')),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Situação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolved', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('created_label', models.CharField(blank=True, max_length=200, verbose_name='Resultado')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_writes', to='app.conversation', verbose_name='Conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_writes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lançamento Pendente',
                'verbose_name_plural': 'Lançamentos Pendentes',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
