# Generated by Django 6.0.8 on 2026-09-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_installment_installments_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='installment',
            name='installment_value_positive',
        ),
    ]
