# Generated by Django 6.0.8 on 2026-09-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_installment_installment_value_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
    ]
