# Generated by Django 6.0.8 on 2026-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_transaction_api_token_conversation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tool_call_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tool_calls',
        ),
        migrations.AddField(
            model_name='message',
            name='items',
            field=models.JSONField(blank=True, default=list, verbose_name='Itens da Conversa'),
        ),
    ]
