# Generated by Django 6.0.8 on 2026-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_message_tool_call_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Aparece no Chat'),
        ),
    ]
