# Generated by Django 6.0.8 on 2026-09-12 00:00

from django.db import migrations, models


def delete_subscription_charges(apps, schema_editor):
    Transaction = apps.get_model('app', 'Transaction')
    Transaction.objects.filter(subscription__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_transfer_value'),
    ]

    operations = [
        migrations.RunPython(delete_subscription_charges, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_value_positive',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_recurrence_within_choices',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionperiod',
            name='subscription_period_cancelled_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionperiod',
            name='subscription_period_single_open',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionperiod',
            name='subscription_period_unique_start',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionperiod',
            name='subscription_period_no_overlap',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_single_origin',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_reference_only_within_subscription',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_unique_subscription_reference',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_subscription_charge_is_regular',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_charge_within_reference',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment__isnull', False), ('transfer__isnull', False), _negated=True), name='transaction_single_origin', violation_error_message='Uma transação vem de um parcelamento ou de uma transferência, nunca dos dois.'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPeriod',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
