# Generated by Django 6.0.8 on 2026-09-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_subscription_subscription_value_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['IN', 'OUT'])), name='transaction_type_within_choices', violation_error_message='O tipo precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['CREDIT', 'DEBIT', 'NOT_APPLICABLE'])), name='transaction_method_within_choices', violation_error_message='O método precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('nature__in', ['REGULAR', 'INTERNAL', 'ADJUSTMENT'])), name='transaction_nature_within_choices', violation_error_message='A natureza precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('parcel__isnull', True), ('parcel__gte', 1), _connector='OR'), name='transaction_parcel_positive', violation_error_message='O número da parcela começa em 1.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('effective_at__gte', models.F('occurred_at'))), name='transaction_effective_after_occurrence', violation_error_message='A data efetiva não pode ser anterior à data da transação.'),
        ),
    ]
