# Generated by Django 6.0.8 on 2026-09-05 22:25

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.DateField(blank=True, null=True, verbose_name='Competência'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='O nome do serviço. Ex.: Spotify, Netflix, Claude.', max_length=200, verbose_name='Assinatura')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mensal')),
                ('charge_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia da Cobrança')),
                ('start', models.DateField(default=datetime.date(2026, 9, 1), verbose_name='Primeira Competência')),
                ('last_reference', models.DateField(blank=True, null=True, verbose_name='Última Competência Gerada')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account', verbose_name='Conta')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.card', verbose_name='Cartão')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.subscription', verbose_name='Assinatura'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('subscription', 'reference'), name='unique_subscription_reference'),
        ),
    ]
