# Generated by Django 6.0.8 on 2026-09-12 01:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_transaction_value_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_transfer_leg_is_internal',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '^\\S(.*\\S)?$')), name='account_description_not_blank', violation_error_message='A descrição não pode ficar em branco nem começar ou terminar com espaço.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '^\\S(.*\\S)?$')), name='category_description_not_blank', violation_error_message='A descrição não pode ficar em branco nem começar ou terminar com espaço.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nature', 'ADJUSTMENT'), _negated=True), ('method', 'NOT_APPLICABLE'), _connector='OR'), name='transaction_adjustment_without_method', violation_error_message='Um ajuste de saldo não tem método, use Não Se Aplica.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'CREDIT'), ('effective_at', models.F('occurred_at')), _connector='OR'), name='transaction_effective_equals_occurrence_outside_credit', violation_error_message='Fora do Crédito, a data efetiva é a própria data da transação.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment__isnull', True), models.Q(('method', 'CREDIT'), ('type', 'OUT')), _connector='OR'), name='transaction_parcel_is_credit_expense', violation_error_message='A parcela de um parcelamento é sempre saída em Crédito.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nature', 'INTERNAL'), ('transfer__isnull', False)), models.Q(('transfer__isnull', True), models.Q(('nature', 'INTERNAL'), _negated=True)), _connector='OR'), name='transaction_internal_only_within_transfer', violation_error_message='A natureza Movimentação Interna é exclusiva das pernas de uma transferência.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer__isnull', True), models.Q(('method', 'DEBIT'), ('type', 'OUT')), models.Q(('method', 'NOT_APPLICABLE'), ('type', 'IN')), _connector='OR'), name='transaction_transfer_leg_methods', violation_error_message='A saída da transferência é em débito e a entrada não se aplica.'),
        ),
        migrations.AlterConstraint(
            model_name='user',
            name='user_unique_email_case_insensitive',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='user_unique_email_case_insensitive', violation_error_message='Já existe um usuário com este e-mail.'),
        ),
    ]
