# Generated by Django 6.0.8 on 2026-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_transaction_reference_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recurrence',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Recorrência'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Cobrança'),
        ),
    ]
