# Generated by Django 6.0.8 on 2026-09-06 01:01

import app.utils.dates
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_subscription_recurrence_alter_subscription_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start',
        ),
        migrations.AddField(
            model_name='subscription',
            name='anchor_month',
            field=models.PositiveSmallIntegerField(default=app.utils.dates.current_month, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês da Primeira Cobrança'),
        ),
    ]
