# Generated by Django 6.0.8 on 2026-09-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido de Acesso',
                'verbose_name_plural': 'Pedidos de Acesso',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['ip', '-created_at'], name='access_request_ip_idx')],
            },
        ),
    ]
