# Generated by Django 6.0.8 on 2026-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_accessrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_nature_within_choices',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('REGULAR', 'Normal'), ('INTERNAL', 'Movimentação Interna'), ('ADJUSTMENT', 'Ajuste de Saldo'), ('INVESTMENT', 'Investimento')], default='REGULAR', max_length=20, verbose_name='Natureza'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('nature__in', ['REGULAR', 'INTERNAL', 'ADJUSTMENT', 'INVESTMENT'])), name='transaction_nature_within_choices', violation_error_message='A natureza precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nature', 'INVESTMENT'), _negated=True), ('method__in', ['DEBIT', 'NOT_APPLICABLE']), _connector='OR'), name='transaction_investment_without_credit', violation_error_message='Um investimento é sempre em Débito ou Não Se Aplica.'),
        ),
    ]
