# Generated by Django 6.0.8 on 2026-09-13 22:38

from django.db import migrations, models


# Ajuste de saldo e movimentação interna faziam a mesma coisa com nomes
# diferentes: os dois só mexem no saldo. O investimento volta a ser Normal, e a
# categoria dele fica para o usuário escolher. Roda com as constraints antigas
# já removidas, porque a de antes recusava Interna fora de transferência.
def merge_natures(apps, schema_editor):
    Transaction = apps.get_model('app', 'Transaction')
    Transaction.objects.filter(nature='ADJUSTMENT').update(nature='INTERNAL')
    Transaction.objects.filter(nature='INVESTMENT').update(nature='REGULAR')


# A volta só consegue separar o ajuste: a Interna avulsa era ajuste, e a de
# transferência já era Interna. O investimento convertido não tem como voltar.
def split_natures(apps, schema_editor):
    Transaction = apps.get_model('app', 'Transaction')
    Transaction.objects.filter(nature='INTERNAL', transfer__isnull=True).update(nature='ADJUSTMENT')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_transaction_nature_investment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_adjustment_without_method',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_internal_only_within_transfer',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_nature_within_choices',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_investment_without_credit',
        ),
        migrations.RunPython(merge_natures, split_natures),
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('REGULAR', 'Normal'), ('INTERNAL', 'Interna')], default='REGULAR', max_length=20, verbose_name='Natureza'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('nature__in', ['REGULAR', 'INTERNAL'])), name='transaction_nature_within_choices', violation_error_message='A natureza precisa ser uma das opções previstas.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'CREDIT'), ('nature', 'INTERNAL'), _negated=True), name='transaction_internal_without_credit', violation_error_message='A natureza Interna só mexe no saldo e nunca é em Crédito.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer__isnull', True), ('nature', 'INTERNAL'), _connector='OR'), name='transaction_transfer_leg_is_internal', violation_error_message='As pernas de uma transferência são sempre de natureza Interna.'),
        ),
    ]
