# Generated by Django 6.0.8 on 2026-10-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_transaction_natures_regular_and_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('user',), name='card_unique_main_per_user', violation_error_message='Já existe um cartão principal. Desmarque-o antes de escolher outro.'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('is_cancelled', True), ('is_main', True), _negated=True), name='card_main_not_cancelled', violation_error_message='Um cartão cancelado não pode ser o principal.'),
        ),
    ]
