"""
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
from datetime import timedelta
from django.utils.csp import CSP
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', '0') == '1'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS').split(',')

INSTALLED_APPS = [
    'project.admin.OTPAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'reversion',
    'axes',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'project.middleware.PermissionsPolicyMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/0'),
    }
}

PASSWORD_HASHERS = [
    "project.hashers.CustomArgon2PasswordHasher",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]

AXES_FAILURE_LIMIT = 5

AXES_COOLOFF_TIME = timedelta(hours=1)

AXES_RESET_ON_SUCCESS = True

AXES_CLIENT_IP_CALLABLE = 'app.utils.get_ip.get_client_ip'

AXES_LOCKOUT_TEMPLATE = None

AXES_VERBOSE = True

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

USE_TZ = True

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static_root'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media_root'

AUTH_USER_MODEL = 'app.User'

LOGIN_URL = 'app:login'

LOGIN_REDIRECT_URL = 'app:overview'

LOGOUT_REDIRECT_URL = 'app:login'

SESSION_COOKIE_AGE = 60 * 60 * 24

SESSION_SAVE_EVERY_REQUEST = True

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

ADMIN_PANEL_PATH = os.getenv('ADMIN_PANEL_PATH', 'admin')

# O assistente. A chave nunca aparece no cliente: quem fala com o modelo é o
# servidor, e o navegador só recebe o texto que já saiu de lá.
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

OPENAI_MODEL = os.getenv('OPENAI_MODEL')

# O áudio não vai para o modelo do chat: ele não escuta. É transcrito na entrada,
# por um modelo próprio, e o que entra na conversa é o texto — que fica legível
# no histórico e custa uma fração do que custaria mandar o áudio a cada rodada.
OPENAI_TRANSCRIBE_MODEL = os.getenv('OPENAI_TRANSCRIBE_MODEL', 'gpt-4o-transcribe')

# Dias que a foto e o áudio do chat ficam no disco. O que vence é o arquivo: a
# transcrição, a mensagem e o lançamento que a foto gerou são permanentes, e o
# arquivo é o único pedaço pesado que ninguém relê depois de conferido. Zero
# desliga a expiração, e é o que mantém o comportamento de guardar para sempre.
# Quem aplica isto é o comando `prune_attachments`, não a aplicação servindo.
ASSISTANT_ATTACHMENT_RETENTION_DAYS = int(os.getenv('ASSISTANT_ATTACHMENT_RETENTION_DAYS', '30'))

SECURE_CSP = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF],
    'style-src': [CSP.SELF, CSP.UNSAFE_INLINE],
    # O blob: é a foto recém-escolhida, antes de existir no servidor: a prévia no
    # compositor e a miniatura da mensagem que acabou de subir saem da memória do
    # navegador. Sem ele a imagem só aparecia depois de um F5, quando passava a
    # vir da rota de anexo — que é o 'self' aqui.
    'img-src': [CSP.SELF, 'data:', 'blob:'],
    'font-src': [CSP.SELF],
    # O áudio gravado no chat é ouvido antes de ser enviado, e nesse momento ele
    # só existe como blob na memória do navegador — não há URL de onde baixá-lo.
    # Depois de enviado, vem da própria aplicação, pela rota que confere o dono.
    'media-src': [CSP.SELF, 'blob:'],
    'connect-src': [CSP.SELF],
    'form-action': [CSP.SELF],
    'frame-ancestors': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'object-src': [CSP.NONE],
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    SESSION_COOKIE_HTTPONLY = True

    X_FRAME_OPTIONS = 'DENY'

    SECURE_REFERRER_POLICY = 'same-origin'

    # O prefixo __Host- faz o navegador recusar o cookie se ele não vier por
    # HTTPS, com Path=/ e sem Domain. Assim um subdomínio comprometido não
    # consegue plantar um cookie que se passe por este (cookie tossing).
    SESSION_COOKIE_NAME = '__Host-sessionid'

    CSRF_COOKIE_NAME = '__Host-csrftoken'
