# Generated by Django 6.0.8 on 2026-09-12 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('card', 'Cartão'), ('transaction', 'Transação'), ('installment', 'Parcelamento'), ('transfer', 'Transferência')], max_length=20, verbose_name='Registro')),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Editar'), ('delete', 'Apagar')], max_length=20, verbose_name='Ação')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Id do Registro')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Registro na Proposta')),
                ('summary', models.JSONField(verbose_name='Resumo Exibido')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Confirmação'), ('confirmed', 'Confirmada'), ('cancelled', 'Descartada'), ('failed', 'Recusada na Confirmação')], default='pending', max_length=20, verbose_name='Situação')),
                ('result', models.CharField(blank=True, max_length=300, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Resolução')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='assistant.conversation', verbose_name='Conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['card', 'transaction', 'installment', 'transfer'])), name='proposal_kind_within_choices', violation_error_message='O registro precisa ser uma das opções previstas.'), models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'delete'])), name='proposal_action_within_choices', violation_error_message='A ação precisa ser uma das opções previstas.'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'cancelled', 'failed'])), name='proposal_status_within_choices', violation_error_message='A situação precisa ser uma das opções previstas.'), models.CheckConstraint(condition=models.Q(models.Q(('action', 'create'), ('target_id__isnull', True)), models.Q(models.Q(('action', 'create'), _negated=True), ('target_id__isnull', False)), _connector='OR'), name='proposal_target_only_outside_create', violation_error_message='Editar e apagar apontam para um registro; criar, não.')],
            },
        ),
    ]
