# Generated by Django 6.0.8 on 2026-09-12 22:14

import assistant.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio')], max_length=10, verbose_name='Tipo')),
                ('file', models.FileField(max_length=200, upload_to=assistant.models.attachment_path, verbose_name='Arquivo')),
                ('mime', models.CharField(max_length=60, verbose_name='Tipo de Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='assistant.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['image', 'audio'])), name='attachment_kind_within_choices', violation_error_message='O tipo precisa ser uma das opções previstas.')],
            },
        ),
    ]
