# Generated by Django 6.0.8 on 2026-09-14 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('instructions', models.TextField(max_length=2000, verbose_name='Instruções')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_commands', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['name'],
                'permissions': [('command_limit_10', 'Can have up to 10 commands'), ('command_limit_20', 'Can have up to 20 commands'), ('unlimited_commands', 'Can have unlimited commands')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='command_unique_user_name', violation_error_message='Você já tem um comando com esse nome.'), models.CheckConstraint(condition=models.Q(('name__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='command_name_is_slug', violation_error_message='O nome precisa ter letras ou números, separados só por hífen.')],
            },
        ),
    ]
