# Generated by Django 6.0.8 on 2026-09-15 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_command'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Dia')),
                ('messages', models.PositiveIntegerField(default=0, verbose_name='Mensagens Enviadas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Uso Diário',
                'verbose_name_plural': 'Usos Diários',
                'ordering': ['-day', 'user'],
                'permissions': [('message_limit_50', 'Can send up to 50 messages a day'), ('message_limit_100', 'Can send up to 100 messages a day'), ('unlimited_messages', 'Can send unlimited messages a day')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='daily_usage_unique_user_day', violation_error_message='Este usuário já tem a contagem deste dia.')],
            },
        ),
    ]
